### ISSUE TITLE
Why is the NFC permission required?

### ISSUE THREAD

**Issue by TjWallas** [vojta-horanek/APKMirror#20]
I don't believe the [NFC permission](https://github.com/vojta-horanek/APKMirror/blob/master/app/src/main/AndroidManifest.xml#L7) would be required for the core functionalities to download and browse APKs on APK mirror.

Is there a specific reason why the app needs this permission?

**Comment by vojta-horanek** [comment]
If you look at my code there is a feature for sharing the current web page with Android Beam. I do not use this permission for anything harmful.

**Comment by TjWallas** [comment]
@vojta-horanek Thanks. I did look at the code and realized you are doing so. However, I still believe that this feature is "nice to have" and not completely necessary. Privacy-concerned users might want to live without this feature or completely disable it.
