### ISSUE TITLE
Release APK on Fdroid?

### ISSUE THREAD

**Issue by TjWallas** [vojta-horanek/APKMirror#21]
I understand your motives behind not releasing on the Google Play store from #6.

[Fdroid](https://f-droid.org/) is quite a popular and attractive app store for free and opensource applications. APKs there are briefly audited by the community and do not require a developer fee nor, demand personal information intrusively for publishing an app.

Could you release on Fdroid? This might also give the app a lot more publicity and potentially attract a larger user base.

You can read about [Fdroid submission policies](https://f-droid.org/wiki/page/Inclusion_Policy) and then, submit your app here: https://f-droid.org/forums/forum/submission-queue/

**Comment by vojta-horanek** [comment]
Thanks, i will conciser that.

**Comment by vojta-horanek** [comment]
OK, so i've just read the submission policies and i cannot post my app there since i use some proprietary software (Firebase, Ad mob..)

**Comment by TjWallas** [comment]
@vojta-horanek I see. Well... it is one alternative route to go, if you decide to be completely third-party-free and truly FOSS.

Perhaps you could find another more interesting revenue stream through donations from the community (e.g. Bitcoin, Paypal) compared to ads and analytics. Also, you could still offer your app as a paid app on Google Play later on once you decide to do so.

**Comment by IzzySoft** [comment]
@vojta-horanek I've [added it to my repo](https://apt.izzysoft.de/fdroid/index/apk/cf.vojtechh.apkmirror) (which can be used with the F-Droid client) – but I cannot fetch the latest version, as you forgot to attach the `.apk` to release 3.3. Could you please fill the gap?

**Comment by vojta-horanek** [comment]
Thanks a lot! Added the apk, sorry - [3.3](https://github.com/vojta-horanek/APKMirror/releases/tag/3.3)

**Comment by IzzySoft** [comment]
Thanks a lot! Then my repo should auto-update it with the next run before I'm back home to check 😺

**Comment by IzzySoft** [comment]
Confirmed, auto-updater picked it. Thanks again!

**Comment by vojta-horanek** [comment]
No problem, thanks to you, I really appreciate posting my app on your repo :)
