### ISSUE TITLE
None web-version of apkmirror

### ISSUE THREAD

**Issue by AxiK101** [vojta-horanek/APKMirror#27]
Is this possible? All apkmirror apps are actually loading the webpage. Can you make a stand alone app like for example ApkPure has? Thanks

**Comment by vojta-horanek** [comment]
Well I can but I can't aswell. I could make the app but I can't release it.

Sorry

**Comment by AxiK101** [comment]
you can't release it in plsystore i suppose, but what if you release it on xda?

**Comment by vojta-horanek** [comment]
Nope, I can't release it anywhere, I can't tell you the reason but I really
can't. Sorry :/
