### ISSUE TITLE
APK MIRROR

### ISSUE THREAD

**Issue by diehard88** [vojta-horanek/APKMirror#37]
was abandoned and now it feels alone.

**Comment by xewelmafi** [comment]
I want this

**Comment by Grossdm** [comment]
@xewelmafi, you have a couple options for the last release/build of this app.

Here you go:

The actual GitHub listing, https://github.com/vojta-horanek/APKMirror/releases
or if you use F-Droid (which I like for FLOSS)
APKMirror (APKMirror client) - https://f-droid.org/app/cf.vojtechh.apkmirror

Does that help?
❓ 😃

**Comment by diehard88** [comment]
danke danke.

**Comment by Grossdm** [comment]
Bitte.

**Comment by Grossdm** [comment]
@diehard88, perhaps you should consider closing this issue.

Does that seem reasonable?

**Comment by diehard88** [comment]
schlossen
